acu/urls.py
__author__ = 'jay'

from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required

from .views import *

urlpatterns = patterns('',

    #--------------------------------------------------------------------------------------------------
    # General Views
    #--------------------------------------------------------------------------------------------------
    url(r'^$',
        login_required(Index_View.as_view()),
        name="Index_View"),

    #--------------------------------------------------------------------------------------------------
    # List Views
    #--------------------------------------------------------------------------------------------------
    url(r'^venues/$',
        login_required(ListVenue_View.as_view()),
        name="ListVenue_View"),

    #--------------------------------------------------------------------------------------------------
    # Create/Edit Views
    #--------------------------------------------------------------------------------------------------
    url(r'^venues/create/$',
        login_required(CreateVenue_View.as_view()),
        name="CreateVenue_View"),

)

football/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.contrib import admin

from acu.views import Index_View

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'football.views.home', name='home'),
    # url(r'^football/', include('football.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^login/$', login, name="Login_View"),
    url(r'^logout/$', logout_then_login, name="Logout_View"),
    url(r'^$', login_required(Index_View.as_view()), name="Index_View"),

    url(r'^acu/', include('acu.urls', namespace='acu', app_name='acu')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

acu/models/core.py
__author__ = 'jay'

import datetime

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from acu import constants as acuCon

class ACUBaseModel(models.Model):

    class Meta:
        abstract = True
        app_label = 'acu'

class Contact(ACUBaseModel):

    user = models.OneToOneField('auth.User')
    type = models.CharField(max_length=64, choices= acuCon.CONTACT_TYPE_CHOICES, default=acuCon.CONTACT_TYPE_PLAYER)

    def __unicode__(self):
        """Gets string representation of the model instance"""
        return "%s %s" % (self.user.first_name,self.user.last_name)

    def is_admin(self):
        return True if self.type == acuCon.CONTACT_TYPE_ADMIN else False

    class Meta:
        app_label = 'acu'
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

def create_contact(sender, instance, created, **kwargs):
    if created:
        profile, created = Contact.objects.get_or_create(user=instance)

post_save.connect(create_contact, sender=User)
User.contact = property(lambda u: u.get_profile())

class Player(ACUBaseModel):

    contact = models.ForeignKey('acu.Contact')
    event = models.ForeignKey('acu.Event')
    team = models.ForeignKey('acu.Team')

    def __unicode__(self):
        """Gets string representation of the model instance"""
        return "%s - %s" % (self.team.name,self.contact)

    class Meta:
        app_label = 'acu'
        verbose_name = "Player"
        verbose_name_plural = "Players"
        unique_together = ("contact", "team")

class Team(ACUBaseModel):

    name = models.CharField(max_length=255, blank=True, null=True)
    event = models.ForeignKey('acu.Event')
    description = models.TextField(max_length=2048, blank=True, null=True)

    def __unicode__(self):
        """Gets string representation of the model instance"""
        return "%s" % (self.name)

    class Meta:
        app_label = 'acu'
        verbose_name = "Team"
        verbose_name_plural = "Teams"

class Venue(ACUBaseModel):

    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(max_length=2048, blank=True, null=True)
    featured_image = models.ImageField(upload_to='images/venues/featured/%Y/%m/%d', blank=True, null=True)

    def __unicode__(self):
        """Gets string representation of the model instance"""
        return "%s" % (self.name)

    class Meta:
        app_label = 'acu'
        verbose_name = "Venue"
        verbose_name_plural = "Venues"

class Event(ACUBaseModel):

    name = models.CharField(max_length=255, blank=True, null=True)
    type = models.CharField(max_length=64, choices=acuCon.EVENT_TYPE_CHOICES, default=acuCon.EVENT_TYPE_REGULAR)
    description = models.TextField(max_length=2048, blank=True, null=True)
    start_date = models.DateField(default=datetime.datetime.today())
    end_date = models.DateField(default=datetime.datetime.today())

    def __unicode__(self):
        """Gets string representation of the model instance"""
        return "%s" % (self.name)

    class Meta:
        app_label = 'acu'
        verbose_name = "Event"
        verbose_name_plural = "Events"

class Game(ACUBaseModel):

    event = models.ForeignKey('acu.Event')
    description = models.TextField(max_length=2048, blank=True, null=True)
    game_date = models.DateField(default=datetime.datetime.today())
    home_team = models.ForeignKey('acu.Team', related_name='home_game_set')
    away_team = models.ForeignKey('acu.Team', related_name='away_game_set')
    home_score = models.IntegerField(blank=True, null=True)
    away_score = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        """Gets string representation of the model instance"""
        return "%s - %s" % (self.event.name,self.game_date)

    class Meta:
        app_label = 'acu'
        verbose_name = "Game"
        verbose_name_plural = "Games"

class Stat(ACUBaseModel):

    player = models.ForeignKey('acu.Player')
    game = models.ForeignKey('acu.Game')
    goals = models.IntegerField(default=0)

    def __unicode__(self):
        """Gets string representation of the model instance"""
        return "Stat(%s):%s - %s" % (self.id,self.player,self.game)

    class Meta:
        app_label = 'acu'
        verbose_name = "Stat"
        verbose_name_plural = "Stats"
        unique_together = ("player", "game")

acu/views/common.py
__author__ = 'jay'

from django.views.generic import (TemplateView, FormView, CreateView, UpdateView, ListView, DetailView)

from acu import models as acuMod

class Index_View(TemplateView):
    template_name = "acu/index.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Index_View, self).get_context_data(**kwargs)

        #profile = self.request.user.get_profile()

        context['contact'] = self.request.user.contact

        return context

acu/views/create_edit.py
__author__ = 'jay'

from django.views.generic import (TemplateView, FormView, CreateView, UpdateView, ListView, DetailView)
from django.core.urlresolvers import reverse

from acu import models as acuMod

class CreateVenue_View(CreateView):
    model = acuMod.Venue
    template_name = "acu/create/create_venue.html"
    success_url = '/'

    def form_invalid(self, form):
        return super(CreateVenue_View, self).form_invalid(form)

acu/views/list.py
__author__ = 'jay'

from django.views.generic import (TemplateView, FormView, CreateView, UpdateView, ListView, DetailView)
from django.core.urlresolvers import reverse
from django.db.models import Q

from acu import models as acuMod

class ListVenue_View(ListView):
    model = acuMod.Venue
    context_object_name = "venues"
    template_name = "acu/lists/venues.html"

    extra_refer ="&searchTerm=%s&col=%s&ot=%s"
    header_refer = "&searchTerm=%s"

    paginate_by = 10
    default_status = int(0)

    col_field_map = {1:'name',
                     2:'description',
                     }

    def get_queryset(self):

        profile = self.request.user.get_profile()

        venues = acuMod.Venue.objects.all()

        # If the user entered a search term, filter by that term
        search_term = self.request.GET.get('searchTerm', None)
        if search_term:
            venues = venues.filter(Q(name__icontains=search_term) | Q(description__icontains=search_term))

        defaultSort="desc"
        sortOrder = self.request.GET.get('ot', ('desc' if defaultSort=='desc' else 'asc'))
        nextOrder = ('asc' if sortOrder=='desc' else 'desc')
        self.sortOrder = sortOrder
        self.nextOrder = nextOrder

        #Order columns based on Header information
        #get column number - use Name of campaign if not found
        column = self.request.GET.get('col', 1)

        try:
            column = int(column)
        except ValueError:
            column = 1

        self.column = column

        asc = False
        if sortOrder == 'asc':
            asc = True

        sortField = self.col_field_map[column] if asc else "-" + self.col_field_map[column]

        venues = venues.order_by(sortField)

        return venues

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ListVenue_View, self).get_context_data(**kwargs)

        context['search_term'] = self.request.GET.get('searchTerm', "")
        context['col'] = self.column
        context['nextOrder'] = self.nextOrder
        context['sortOrder'] = self.sortOrder
        context['header_refer'] = self.header_refer % (context['search_term'])
        context['extra_refer'] = self.extra_refer % (context['search_term'], context['col'], context['sortOrder'] )

        #if self.request.is_ajax():
        #    self.template_name = "up_audience_activator/proposals/proposal_list_table.html"

        return context

acu/templates/acu/acu_base.html
{% extends "global_base.html" %}
{% load url from future %}

{% block base-css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}acu/blueprint/ie.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}acu/blueprint/screen.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}acu/css/ui-darkness/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}acu/css/jmenu/jMenu.jquery.css" />

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}acu/css/acu_global.css" />
{% endblock %}

{% block base-js %}
    <script type="text/javascript" src="{{ STATIC_URL }}acu/js/jquery.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}acu/js/jquery-ui.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}acu/js/jMenu.jquery.js"></script>

    <script type="text/javascript">
        $(document).ready(function(){
            $("#menu").jMenu();
        });
    </script>
{% endblock %}

{% block body %}
    <div id="body-container" class="container">
        <div id="header-container" class="container">
            <div id="header-menu" class="span-8 append-12">
                <ul id="menu">
                    <li>
                        <a class="fNiv menu-item" href="{% url 'acu:Index_View' %}">Home</a>
                    </li>
                    <li>
                        <a class="fNiv menu-item">Events</a>
                        {% if user.get_profile.is_admin %}
                            <ul>
                                <li class="arrow"></li>
                                <li><a class="menu-item">Event Listing</a></li>
                                <li><a class="menu-item">Add New Event</a></li>
                            </ul>
                        {% endif %}
                    </li>
                    <li>
                        <a class="fNiv menu-item">Venues</a>
                        {% if user.get_profile.is_admin %}
                            <ul>
                                <li class="arrow"></li>
                                <li><a class="menu-item" href="{% url 'acu:ListVenue_View' %}">Venue Listing</a></li>
                                <li><a class="menu-item" href="{% url 'acu:CreateVenue_View' %}">Add New Venue</a></li>
                            </ul>
                        {% endif %}
                    </li>
                    <li>
                        <a class="fNiv menu-item">Games</a>
                    </li>
                    <li>
                        <a class="fNiv menu-item">Teams</a>
                    </li>
                    <li>
                        <a class="fNiv menu-item" href="{% url 'acu:Index_View' %}">Contact</a>
                    </li>
                </ul>
            </div>
            <div id="tools" class="span-4 last">
                <div style="float: left;">
                    {% if user.is_authenticated %}
                        <span>Hello, {{ user.first_name }}</span>
                    {% endif %}
                </div>
                <div style="float: right;">
                    {% if user.is_authenticated %}
                        <a href="/logout" class="menu-item">Logout</a>
                    {% else %}
                        <a href="/login" class="menu-item">Login</a>
                    {% endif %}
                </div>
                <div style="clear: both;"></div>
            </div>
        </div>
        <div id="breadcrumbs-container" class="container">
            {% block breadcrumbs %}
                <span>Home</span>
            {% endblock %}
        </div>
        <div id="content_container" class="container">
            <div id="content">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

acu/templates/acu/index.html
{% extends "acu/acu_base.html" %}
{% load url from future %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function(){
        });
    </script>
{% endblock %}

{% block breadcrumbs %}
    <span>Home</span>
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Hello</h1>
        <div class="span-12">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rutrum justo quis orci rutrum sagittis. Vivamus sit amet massa eget tortor consectetur pharetra eu vitae mauris. In mattis lobortis dui, eu aliquam enim commodo et. Pellentesque ac nibh arcu, non rhoncus metus. Maecenas lacinia facilisis lacinia. Sed malesuada leo id dui blandit gravida. Duis dapibus eros vitae erat faucibus fringilla. Donec ac turpis in erat malesuada ultricies id in nisl. Maecenas ipsum felis, tempor in ultricies convallis, ornare tristique libero. Cras sit amet varius nunc.</p>
            <p>Nulla id nibh urna. Nam eros nulla, ullamcorper eget convallis sed, placerat quis elit. Nunc ac libero nisi. Ut vestibulum consectetur varius. Cras egestas, augue nec varius hendrerit, nibh sem placerat dolor, nec suscipit nulla nisl at elit. Nullam congue lacus vitae sapien sollicitudin eu vehicula nisi viverra. Sed dapibus scelerisque mauris nec vestibulum. Aenean diam velit, tempus in ultricies in, molestie eu augue.</p>
            <p>Sed ut tellus justo, non laoreet ligula. Vivamus pulvinar sapien ac dolor feugiat ut egestas felis suscipit. Phasellus quis libero libero, in accumsan libero. Vivamus ultrices mollis mauris at blandit. Quisque orci dui, aliquet sed interdum adipiscing, dictum vitae orci. Nullam aliquam urna in lacus viverra at vulputate lorem ultricies. Aenean elementum lorem non sapien tempor lobortis. Praesent faucibus libero vitae urna vulputate sagittis. Quisque placerat placerat purus, non vestibulum est euismod eget. Suspendisse eget sapien vitae arcu hendrerit posuere.</p>
            <p>Aenean luctus commodo metus non laoreet. Nulla facilisi. Aenean tempor tincidunt mi, mollis condimentum erat gravida eu. Fusce varius nunc nec massa sagittis accumsan. Donec gravida ultrices tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut tempus, odio id sollicitudin mollis, risus lorem condimentum nibh, id eleifend augue velit vitae massa. Duis et neque non ligula euismod euismod. Aenean consectetur ultrices magna, a consequat nulla tempus sit amet. Duis eleifend lobortis nibh, ac commodo nibh rutrum at. Praesent tempus, ante eu viverra tincidunt, ligula ligula adipiscing augue, et pellentesque nisi turpis id quam. Sed ultrices vestibulum massa, at imperdiet arcu pretium id.</p>
            <p>Aenean ultrices consequat mauris, sit amet tristique nisl rhoncus et. Nullam tristique rhoncus nibh eget congue. Ut a neque accumsan tortor sodales fringilla vitae nec enim. Proin eu nisi nibh, ac lacinia arcu. Curabitur tortor tortor, eleifend id vestibulum sed, eleifend ut neque. Etiam malesuada lorem sit amet eros vulputate pellentesque. Curabitur ullamcorper lectus sed massa laoreet elementum vel eu quam. Etiam id sem est. Nulla facilisis, magna nec rhoncus luctus, nisi urna cursus quam, quis dapibus turpis massa sit amet purus. Donec nec porttitor magna. Vestibulum aliquam mauris a urna consequat faucibus. Cras sed felis sed arcu faucibus laoreet quis vitae est. Aliquam erat volutpat. In hac habitasse platea dictumst. Etiam eu felis in urna tincidunt posuere eu vitae leo. Mauris ullamcorper dapibus lorem, feugiat aliquam augue adipiscing id.</p>
        </div>
        <div class="span-12 last">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rutrum justo quis orci rutrum sagittis. Vivamus sit amet massa eget tortor consectetur pharetra eu vitae mauris. In mattis lobortis dui, eu aliquam enim commodo et. Pellentesque ac nibh arcu, non rhoncus metus. Maecenas lacinia facilisis lacinia. Sed malesuada leo id dui blandit gravida. Duis dapibus eros vitae erat faucibus fringilla. Donec ac turpis in erat malesuada ultricies id in nisl. Maecenas ipsum felis, tempor in ultricies convallis, ornare tristique libero. Cras sit amet varius nunc.</p>
            <p>Nulla id nibh urna. Nam eros nulla, ullamcorper eget convallis sed, placerat quis elit. Nunc ac libero nisi. Ut vestibulum consectetur varius. Cras egestas, augue nec varius hendrerit, nibh sem placerat dolor, nec suscipit nulla nisl at elit. Nullam congue lacus vitae sapien sollicitudin eu vehicula nisi viverra. Sed dapibus scelerisque mauris nec vestibulum. Aenean diam velit, tempus in ultricies in, molestie eu augue.</p>
            <p>Sed ut tellus justo, non laoreet ligula. Vivamus pulvinar sapien ac dolor feugiat ut egestas felis suscipit. Phasellus quis libero libero, in accumsan libero. Vivamus ultrices mollis mauris at blandit. Quisque orci dui, aliquet sed interdum adipiscing, dictum vitae orci. Nullam aliquam urna in lacus viverra at vulputate lorem ultricies. Aenean elementum lorem non sapien tempor lobortis. Praesent faucibus libero vitae urna vulputate sagittis. Quisque placerat placerat purus, non vestibulum est euismod eget. Suspendisse eget sapien vitae arcu hendrerit posuere.</p>
            <p>Aenean luctus commodo metus non laoreet. Nulla facilisi. Aenean tempor tincidunt mi, mollis condimentum erat gravida eu. Fusce varius nunc nec massa sagittis accumsan. Donec gravida ultrices tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut tempus, odio id sollicitudin mollis, risus lorem condimentum nibh, id eleifend augue velit vitae massa. Duis et neque non ligula euismod euismod. Aenean consectetur ultrices magna, a consequat nulla tempus sit amet. Duis eleifend lobortis nibh, ac commodo nibh rutrum at. Praesent tempus, ante eu viverra tincidunt, ligula ligula adipiscing augue, et pellentesque nisi turpis id quam. Sed ultrices vestibulum massa, at imperdiet arcu pretium id.</p>
            <p>Aenean ultrices consequat mauris, sit amet tristique nisl rhoncus et. Nullam tristique rhoncus nibh eget congue. Ut a neque accumsan tortor sodales fringilla vitae nec enim. Proin eu nisi nibh, ac lacinia arcu. Curabitur tortor tortor, eleifend id vestibulum sed, eleifend ut neque. Etiam malesuada lorem sit amet eros vulputate pellentesque. Curabitur ullamcorper lectus sed massa laoreet elementum vel eu quam. Etiam id sem est. Nulla facilisis, magna nec rhoncus luctus, nisi urna cursus quam, quis dapibus turpis massa sit amet purus. Donec nec porttitor magna. Vestibulum aliquam mauris a urna consequat faucibus. Cras sed felis sed arcu faucibus laoreet quis vitae est. Aliquam erat volutpat. In hac habitasse platea dictumst. Etiam eu felis in urna tincidunt posuere eu vitae leo. Mauris ullamcorper dapibus lorem, feugiat aliquam augue adipiscing id.</p>
        </div>
    </div>
{% endblock %}